"""create transaction and add columns

Revision ID: d57dc0b4824b
Revises: c37b749781d5
Create Date: 2024-03-21 03:06:36.117320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57dc0b4824b'
down_revision: Union[str, None] = 'c37b749781d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('payment_system', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_reference_number'), 'transaction', ['reference_number'], unique=False)
    op.add_column('project', sa.Column('is_verified', sa.Boolean(), nullable=True)) # Populated non nullable column
    # ### end Alembic commands ###
    
    op.execute("UPDATE project SET is_verified = True") # Fix populated non nullable column
    op.alter_column('project', 'is_verified', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_verified')
    op.drop_index(op.f('ix_transaction_reference_number'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
